insert into razas (raza) values ('Bulldog');
insert into razas (raza) values ('Salchicha');
insert into razas (raza) values ('Border Colli');
insert into razas (raza) values ('Colli');
insert into razas (raza) values ('Caniche');
insert into razas (raza) values ('Maltés');
insert into razas (raza) values ('Chihuahua');
insert into razas (raza) values ('Pomerania');
insert into razas (raza) values ('Siberiano');
insert into razas (raza) values ('Chow Chow');
insert into razas (raza) values ('Labrador');
insert into razas (raza) values ('Golden');
insert into razas (raza) values ('Schnauzer');
insert into razas (raza) values ('Setter irlandés');
insert into razas (raza) values ('Boyero');
insert into razas (raza) values ('Gran danés');
insert into razas (raza) values ('Cocker');
insert into razas (raza) values ('Pitbull');
insert into razas (raza) values ('Cocker');
insert into razas (raza) values ('Mastín Napolitano');
insert into razas (raza) values ('Galgo');
insert into razas (raza) values ('shitzu');
